### ISSUE TITLE
PQLite: benchmark storage engine

### ISSUE THREAD

**Issue by numb3r3** [jina-ai/pqlite#54]
benchmark among: the goal is to **make a decision which storage engine to use in qplite**:

- LMDB
- DAM
- Rocksdb

**Comment by numb3r3** [comment]
The benchmark result:
```
total time pqlite=38.99 seconds
total time docarraymemmap=39.58 seconds
```

**Comment by davidbp** [comment]
This result (https://github.com/jina-ai/pqlite/pull/57)  is only about insert times and suggests the slowdown in indexing of pqlite is not due to inserting data.
