### ISSUE TITLE
Feat: Additional filters

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/pqlite#71]
I was just chatting with @davidbp about filtering in PQLite. For my [fashion search example](http://examples.jina.ai/fashion/) I'm looking at adding filters (similar to Amazon) to pre-filter results. This work is being done in a [separate branch](https://github.com/alexcg1/jina-multimodal-fashion-search/tree/migrate-pqlite) of my repo.

At present I'm able to easily search in ranges (e.g. price, year), or above a certain threshold (e.g. rating):

```python
filter = {
    "$and": {
        "year": {"$gte": 2011, "$lte": 2014},
        "price": {"$gte": 100, "$lte": 200},
        "rating": {"$gte": 3},
    },
}
```

But what would be really useful is a *convenient* way to search for AND and XOR. 

## Current implementation

Previously I tried something (which actually works) like:

```python
filter = {
    "$and": {
        "year": {"$lte": 2014, "$gte": 2011},
        "price": {"$gte": 0, "$lte": 200},
    },
    "$or": {
        "baseColour": {"$eq": "Black"},
        "$or": {
            "baseColour": {"$eq": "White"},
            "$or": {
                "baseColour": {"$eq": "Blue"}
            }
        }
    }
}
```

But this is:

1. Inelegant
2. A real pain to build programmatically (i.e. by taking into account checked boxes on my frontend)

## Desired implementation

Some new operators: `$one_of` and `$all_of`

```python
filter = {
    "$and": {
        "year": {"$gte": 2011, "$lte": 2014},
        "price": {"$gte": 100, "$lte": 200},
        "rating": {"$gte": 3},
        "baseColour": {"$one_of": ['White', 'Blue', 'Black']},
        "season": {"$all_of": ['Summer', 'Spring', 'Fall']},
    },
}
```

## Other thoughts

In Commsor (our community analysis tool) we use a lot of filters are useful in real world:
![image](https://user-images.githubusercontent.com/4182659/146566539-462aa13e-fadd-4104-b6aa-cf5a81c85ffc.png)

So I'd also like to propose the following operators:

- `$contains`
- `$notcontains` (e.g. we often want to filter out universities since we focus on enterprises, so we would say `company_name $notcontains "university"`)

## Notes

- Rating and price aren't in the original dataset (as used by @bwanglzu in his notebook). I generated them programmatically to give us a richer dataset to play with

**Comment by alexcg1** [comment]
@davidbp @numb3r3 assigning you since I don't know who else to assign :)

**Comment by numb3r3** [comment]
@alexcg1 The membership operator `$in` (i.e., `$one_of`) and `$nin` is introduced by this PR https://github.com/jina-ai/pqlite/pull/72 

FYI, the operator name convention is following the MongoDB's style https://docs.mongodb.com/manual/reference/operator/query/#std-label-query-selectors
