### ISSUE TITLE
Clean codebase

### ISSUE THREAD

**Issue by davidbp** [jina-ai/pqlite#80]
From today's meeting we've commented

-  [x]  fix pip in `README`
-  [x]  fix table format (percentage, decimal)
-  [x] use `TYPE_CHECKING` to protect unnecessary input
-  [x] use `from_bytes` and `to_bytes` for reading/writing binary of Document
-  [x] an example of using jina 3 and pqlite to achieve sharding in K8s.

**Comment by numb3r3** [comment]
Except the last ticket, all of the tickets are done
