### ISSUE TITLE
PQLite: DEBUG logging enabled by default

### ISSUE THREAD

**Issue by alexcg1** [jina-ai/pqlite#88]
Not sure if this is deliberate? In `jinahub://PQLiteIndexer/v0.1.3` there's a lot of logging coming up
![image](https://user-images.githubusercontent.com/4182659/148248537-45c210d7-73f6-4fe3-a1af-187fc2b05975.png)

**Comment by alexcg1** [comment]
Logging resulted from using code in [this repo dir](https://github.com/alexcg1/jina-meme-search/tree/main/backend-image)

**Comment by alexcg1** [comment]
Can confirm for 0.1.4 too

**Comment by numb3r3** [comment]
I see, in requirements, the pqlite is install via `git+https://` protocol. Hence, the local installed `pqlite` cannot be upgraded to v0.1.4 from v0.1.3 by using `pip`. This is a pain to use `git+https://` we can see so far. To address this issue, `pqlite` need to be published via **pypi.org**. 

As a quick fix for your problem, you can uninstall pqlite firstly via: `pip uninstall pqlite`
